### ISSUE TITLE
内核没有ifb

### ISSUE THREAD

**Issue by yaleax** [SuzukiHonoka/s905d-kernel-precompiled#14]
我要安装一个项目需要内核有ifb模块，试了试你的内核不包含这个模块。

所以想来请教如何把ifb模块安装到内核里？

谢谢

**Comment by SuzukiHonoka** [comment]
等我有空更新内核config

**Comment by yaleax** [comment]
> 等我有空更新内核config

感谢，我看到你收更新内核，这个内核包含ifb吗？

**Comment by SuzukiHonoka** [comment]
> > 等我有空更新内核config
> 
> 感谢，我看到你有更新内核，这个内核包含ifb吗？

暂时没有，那个是更新版本惯例。你如果急的话可以用make menuconfig来启用你说的feature，然后发PR。

**Comment by yaleax** [comment]
> 

我不着急，等你有时间更新。

**Comment by yaleax** [comment]
> > > 等我有空更新内核config
> 
> > 
> 
> > 感谢，我看到你有更新内核，这个内核包含ifb吗？
> 
> 
> 
> 暂时没有，那个是更新版本惯例。你如果急的话可以用make menuconfig来启用你说的feature，然后发PR。

我需要用哪个文件来make menuconfig？

**Comment by SuzukiHonoka** [comment]
.config

**Comment by SuzukiHonoka** [comment]
已追加
