### ISSUE TITLE
kernel-5.15 和 5.13 的不足

### ISSUE THREAD

**Issue by osnosn** [SuzukiHonoka/s905d-kernel-precompiled#15]
我有两台 N1，一直用的是 kernel-5.0.2，内核的 nft 旧了。  
这几天换用了你的 预编译内核。感觉挺好。  
有几个问题。  
* 使用 kernel-5.15.104     
  我更换了zip包中对应的dtb文件 `meson-gxl-s905d-phicomm-n1.dtb`  
  N1 能够启动起来。网络访问正常。  
  可惜，**缺少 CONFIG_BLK_DEV_LOOP 设备** 。不太方便操作磁盘映像文件。  
  但启动过程，包括启动完成后，插在**HDMI上的显示器**，一直都**没有显示**。  
  不知道是 dtb的问题，还是 5.15就不支持本地console了。  
  我担心，如果在升级系统的过程中，出现问题，没法用本地终端+键盘处理。  
  希望您能解决本地终端，字符界面显示的问题。  
* 退到 kernel-5.13.14   
  也更换了zip包中对应的dtb文件 `meson-gxl-s905d-phicomm-n1.dtb`  
  N1 能正常启动。网络访问正常。本地显示器有显示，键盘可用。  
  可惜，**缺少 ppp, pppoe 的内核模块**，缺少 CONFIG_BLK_DEV_LOOP 设备。  
  这个旧版本，能帮忙加上 ppp 相关的 modules 吗？  
* install_kernel.sh 缺少两句。**建议加上**。  
  ```
  #旧内核需要旧映像，应该备份。只恢复 zImage.old，启动会失败。
  cp /boot/uInitrd /boot/uInitrd.old
  
  # 有的机器，没有这个目录。 cp 命令会出错。
  [ -d /boot/dtb/amlogic ] || mkdir -p /boot/dtb/amlogic
  
  # 如果加上这句更完美了。
  echo 'Check dtb PATH in "/boot/uEnv.ini" before restart.'
  ```

谢谢您的分享。  
期待您的修改。

**Comment by SuzukiHonoka** [comment]
老版本由于没有对应分支已无法维护，请尝试使用最新版本。
关于安装脚本问题，你可以直接PR以便直接merge。
感谢你提出的建议。

**Comment by osnosn** [comment]
您说的最新版本，是 kernel 6.1.42 吗？
在 N1 中替换后，根本启动不起来。

另外，还缺少 CONFIG_BLK_DEV_LOOP 设备 。不太方便操作磁盘映像文件。
losetup 命令不工作。希望加上。

脚本问题，您有空加上吧。PR 我不会。

**Comment by SuzukiHonoka** [comment]
已添加 CONFIG_BLK_DEV_LOOP与 PPP、PPPOE，请尝试使用新版内核测试。

**Comment by osnosn** [comment]
> 已添加 CONFIG_BLK_DEV_LOOP与 PPP、PPPOE，请尝试使用新版内核测试。

谢谢你的更新。   

当时(约一年前)，我测试了好几个不同的内核。   
最终，在 ophub 的内核基础上，编译了一个精简版，自己使用。   
测试，换内核的过程 [记录在这个贴子上](https://www.cnblogs.com/osnosn/p/13994474.html#armbian-567-%E6%88%96-577-%E6%8D%A2%E6%96%B0%E5%86%85%E6%A0%B8)。

**Comment by SuzukiHonoka** [comment]
好的，感谢反馈。
