### ISSUE TITLE
咨询S905X3内核兼容的问题

### ISSUE THREAD

**Issue by shaneZhang** [SuzukiHonoka/s905d-kernel-precompiled#2]
内核虽然是标明了S905D专用，但是我在HK1-Box上尝试安装了一下，S905X3内核的安装了这个目前是稳定正常运行。不知道是否是这两种设备兼容，还是后面会有不可预知的风险？？

**Comment by SuzukiHonoka** [comment]
目前内核配置中仅做了AMLOGIC平台支持，虽然loader地址和dtb适配的是先前p230的，但其他的dtb全是upstream的，未作修改，若能正常稳定运行，问题就不大。
