### ISSUE TITLE
【建议】按照longterm版本号发布

### ISSUE THREAD

**Issue by adminpass** [SuzukiHonoka/s905d-kernel-precompiled#7]
1. 建议版本能按照linux kernel [longterm](https://www.kernel.org/) 版本发布，当前5.10.51（2021-07-19）
2. 希望能增加 [Alpine linux](https://www.alpinelinux.org/) 内核编译支持
- _再次感谢提供s905d kernel编译学习_

**Comment by SuzukiHonoka** [comment]
等待更新版本。

**Comment by SuzukiHonoka** [comment]
已发布 5.15.15 LTS
